### ISSUE TITLE
Knowing when a slider is being used

### ISSUE THREAD

**Issue by Paulbarrios** [aestheticinteractive/Hover-VR-Interface-Kit#23]
Hi, I'm trying to implement a function that requires me to know when a specific slider is being touched. The slider should change its value through both user input and the environment (it´s a timeline slider for video reproduction) so I can't just use the value changed as proof that it's being touched. Is there any method to know when the user starts/stops pressing an slider?

**Comment by zachkinstner** [comment]
Hi @Paulbarrios -- I'm sorry for the delay! GitHub didn't send an email notification for this new issue.

It sounds like [`ISelectableItem.IsStickySelected`](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/blob/v1.1.0/Core/Solution/Hover.Common/Items/ISelectableItem.cs#L9) would work for your needs. Both the "slider" and "sticky" item types use "sticky selection" (requires the cursor to move away from the item to deselect it).

To access this item, find the [`HovercastItem`](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/blob/v1.1.0/Core/Solution/Hover.Cast/Items/HovercastItem.cs) component for your slider, and call `GetItem()` on it. The return type for this method is `BaseItem`, but since you know that this is a slider item, you can safely cast to [`SliderItem`](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/blob/d935f9fa9f624b5d08d343ffc891cd143380a89e/Core/Solution/Hover.Common/Items/Types/SliderItem.cs) or any of its parents/interfaces (like `ISelectableItem`).

**Comment by zachkinstner** [comment]
I'm going to close this issue for now -- please let me know if you have further questions/issues with this.
