### ISSUE TITLE
Source solution Unity scripts issue

### ISSUE THREAD

**Issue by TonyViT** [aestheticinteractive/Hover-VR-Interface-Kit#25]
Don't know if it is a known feature or a bug, but...
I downloaded source code from this repository and built the c# solutions. When I opened the Unity project with Unity 5 64bit, two errors popped out: it is a known Oculus bug for Unity5 (fixed in the latest release) inside file OVRMainMenu.cs... so i fixed the file (the known workaround is change World in WorldSpace in the two error lines).

Then the project built... but demo scene did nothing... so I checked... and all the objects in every scene have "missing script" reference for the hovercast scripts. Maybe all .cs scripts files should be copied somewhere else?

**Comment by zachkinstner** [comment]
Hi @TonyViT -- I'm sorry for the delay. GitHub didn't send an email notification for this new issue.

Currently, I'm still developing the Hover VR project with Unity 4, but I have experimented with building it with Unity 5. I also had to workaround the Oculus issue you mentioned. Aside from that, I've been able to both build the project for Unity 5, and also to use the released build of the project in Unity 5.

The "missing script" issue sounds similar to an issue discussed in the "migration guide" ticket (#21). If so, the solution for this is related to the `.meta` files for the Hover VR DLL files. As a quick workaround, please copy the DLL-related `.meta` files in the latest [release package](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/releases) and paste them into your project.

It's probably a good idea for me to include these `.meta` files in the repository itself, so that developers who are creating builds don't run into this issue.  By the way -- the release builds (linked above) should provide the files you need in case you don't need to perform these builds yourself.

**Comment by TonyViT** [comment]
Ook :)

Have a nice day :)

Il 01/06/2015 15:05, Zach Kinstner ha scritto:

**Comment by zachkinstner** [comment]
Great! I'll keep this issue open for now, as a reminder to include those `.meta` files in the repository.

Thanks for your interest in the project, and of course, I'm always curious to see what developers are building with it! (And as a side note, developers can refer to the [licensing details](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/wiki/Licensing%20Details) regarding Hover VR usage.)
