### ISSUE TITLE
Creating hovercast menu items at runtime

### ISSUE THREAD

**Issue by ahsquared** [aestheticinteractive/Hover-VR-Interface-Kit#35]
I am creating Hovercast menu items at runtime in my Unity app. When I create them I see them in the hierarchy, but they are not rendered in the UI. Is there an initialization step I am missing?

Image shows only two items in the UI, but the hierarchy shows 3, the third is added at runtime:
![hovercast](https://cloud.githubusercontent.com/assets/250325/10641140/f475c2c0-77e5-11e5-8959-5ce58c6bd25d.PNG)

This is the code I'm using for creating the menu item:

```
// hoverMenu set in UI
// movieName is a string
GameObject newMenuEntry = new GameObject();
newMenuEntry.transform.parent = hoverMenu.transform;
newMenuEntry.name = movieName;
HovercastItem newHovercastItem = newMenuEntry.AddComponent<HovercastItem>();
newHovercastItem.Type = HovercastItem.HovercastItemType.Radio;
newHovercastItem.Label = movieName;
newMenuEntry.AddComponent<HovercastItemVisualSettingsStandard>();
```

I also tried setting the hierarchy again at runtime:

```
hierarchy = hoverMenu.GetComponent<HovercastItemHierarchy>();
hovercastSetup = hovercast.GetComponent<HovercastSetup>();
hovercastSetup.ItemHierarchy = hierarchy;
```

Thanks for the help.

**Comment by zachkinstner** [comment]
Hi @ahsquared, the issue is likely related to the "Script Execution Order" settings in Unity. You'll need to add all the items to your scene _before_ the `HovercastSetup.Awake()` method executes. The commit referenced above shows a new example where the menu is constructed in a script, and that script is given (via the Unity editor) a "Script Execution Order" value of `-1`.

To have items that are not always available, you can add them at the very beginning, but then change their visibility as needed. In the [new example code](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/blob/master/Unity/Assets/Hover/Demo/CastTest/DemoProceduralMenuItems.cs), this might look like:

```
IBaseItem item = vHoverItems[3].GetItem();
item.IsVisible = isMyOptionAvailable;
```

However, please note that the visibility only takes effect when you enter a new menu level. For example, you might have a "Details" sub-menu, where the list of displayed items depends upon some option that is selected in the parent menu.

**Comment by ahsquared** [comment]
I was missing putting the code in the awake block instead of start!

Thanks!
