### ISSUE TITLE
Change VR mode to desktop mode. 

### ISSUE THREAD

**Issue by shenfangch** [aestheticinteractive/Hover-VR-Interface-Kit#56]
Hello, thanks for answering my previous question. Is that possible to change Leapmotion VR mode to Desktop mode in the CastCubes demo? I would like to face up my Leapmotion on the table. Thanks in advance.

**Comment by zachkinstner** [comment]
Hi @shenfangch, you'd have to do some manual setup with the scene and the Leap Motion prefab. I'm not sure if Leap really supports the desktop mode anymore, they seem to have shifted their focus to VR.

Here's how you could approach it (in the `CastCubes` scene):

1. Disable the _InputSceneLoaders_ object.
1. Add the **LeapHandController** prefab into the scene.
    1. Attach the `HoverInputLeapMotion` script to this object.
    1. Perform any setup needed (like ensuring it's not in "VR mode" and adding hand models).
    1. Move/rotate the object to the correct position for your desktop.
1. Add a camera to the scene (or use the one in _InputSceneLoaders/None/MainCamera_).

You may need to adjust Hovercast's "active direction" to be more suitable for desktop mode. The `HovercastActiveDirection` component (on the _Hovercast_ object) has settings for the target transform and the range of angles where Hovercast will be visible. You could choose a target transform that is slightly lower than the camera itself, so that Hovercast will become visible when your palm is still tipped downward a little (toward the table). The palm-facing-eyes orientation is bad for Leap Motion's desktop tracking, since it can only see the edge of your hand.

**Comment by shenfangch** [comment]
Really appreciated, Zack!
Merry Christmas!
