### ISSUE TITLE
vive 'Cursor data provider' 

### ISSUE THREAD

**Issue by koffertje** [aestheticinteractive/Hover-VR-Interface-Kit#58]
edit:
so i found out the data scripts needs to be on a game object  and cant be in another scene then the vive scene.

hello,

im working with the hover kit for Vive. but i cant get it working. 
![image](https://cloud.githubusercontent.com/assets/20005379/21582386/9f9a1f16-d055-11e6-8945-a505f46f1365.jpg)

i got it working so far, but i cant add anything to the 'Cursor data provider' 

https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Input-Modules%EA%9E%89-Vive
in this links it says it needs to have the 'Cursors (hoverCursorDataProvider) . i cant add it , and i dont know why.

**Comment by zachkinstner** [comment]
@koffertje, after your edit, is it working for you now?

When using the "multi-scene" approach, you'll see something different in the inspector. This is what I see when I drag-and-drop the `HoverInputModule-Vive` scene into another scene:

![image](https://cloud.githubusercontent.com/assets/3940764/21593331/edc7f88c-d0e3-11e6-8451-2e38f175fa43.png)

![image](https://cloud.githubusercontent.com/assets/3940764/21593322/d2d9f53e-d0e3-11e6-8987-b9d28c81b856.png)

The "scene mismatch" message here is a warning from Unity, but it still works as expected when you play the scene. The "Cursor Data Provider" reference is correct, it's just obscured by this message. Here's what the [Multi Scene Editing docs](https://docs.unity3d.com/Manual/MultiSceneEditing.html) say:

> Cross-scene references are not supported but also not prevented.

---

As a final note, just in case: the `HoverCursorDataProvider` component is included within the **HoverKit** prefab. If this prefab is present in the scene, the input module component (like `HoverInputVive`) will find the `HoverCursorDataProvider` component automatically. That search occurs each frame, until it is successful, because the input module is useless without that reference (it is required to update the cursors).

**Comment by zachkinstner** [comment]
@koffertje, I think you've already discovered this, but just in case: you don't need to use the "input module" scenes in the way I showed in my example. Those scenes make it convenient to switch between input devices, but if you only plan to build for one device, you could do something like this:

1. Drag (or copy/paste) the `[CameraRig]` object from the "input" scene (`HoverInputModule-Vive`) into the "main" scene (`GifAnim-Cursors`).
1. Note that the "Scene mismatch" warning (on the "Cursor Data Provider" property) is gone now, because the input module component is now in the same scene as everything else.
1. Remove the reference to the "input" scene (i.e. stop using multi-scene editing).
