### ISSUE TITLE
How to run the keyboard with leapmotion?

### ISSUE THREAD

**Issue by ZhengzhongSun** [aestheticinteractive/Hover-VR-Interface-Kit#59]
I have read the wiki of Hover-UI-Kit, but I'm still a little confusing about how to setup to interact with the keyboard with leapmotion in Vive. When I git clone the project and open it with Unity 5.5.1f1, I need to import the standard assets of Effect. 
But I found that there are missing prefabs in Scene HoverInputModule-LeapMotion. How could I run it in Vive with leapmotion? Need I import the leapmotion sdk to this Unity project? How to set up it?
![4](https://cloud.githubusercontent.com/assets/13618800/23098842/9344658c-f693-11e6-9ac2-17d14a863edf.PNG)\
Thank you very much!

**Comment by zachkinstner** [comment]
Hi @ZhengzhongSun, the Hover UI Kit project (both its releases and its source) does not include any third-party tools or libraries. So, you'll first need to download and install the Leap Motion SDK into your Unity project. Once you do that, Unity's "Missing Prefab" reference (shown in your screenshot) will be replaced with the Leap Motion prefab.

For reference, the [Input Modules](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Input-Modules) wiki page's first installation step says:

> Install the device-related SDK(s).

The [Input Modules: LeapMotion](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Input-Modules%EA%9E%89-LeapMotion#sdk) wiki page provides a link to download the Leap Motion SDK.

**Comment by zachkinstner** [comment]
You mentioned the dependency on Unity's "standard effects" package. I think you see this because you cloned the entire project, which includes the "Hover Demos" folder. Nothing in the core Hover UI Kit project should depend on "standard effects", however, the demo scenes/scripts do depend on (at least) the "standard effects" Bloom filter for achieving a glow effect.

In general, I would recommend using the [releases](https://github.com/aestheticinteractive/Hover-UI-Kit/releases) (currently v2.0.0-beta) for installing Hover UI Kit into your project. Each release is split into packages, allowing you to easily install (or ignore) specific input modules, interface modules, etc. into your project.

**Comment by ZhengzhongSun** [comment]
Thank you very much! You have explained these problems very detailed!
Now, I have impoted the leapmotion sdk into the unity project and the components in Scene HoverInputModule-LeapMotion came out. But there is also an error, in LMHeadMountedRig, the Hover Input Leap Motion has some comile errors.
![1](https://cloud.githubusercontent.com/assets/13618800/23205978/eba92b6e-f926-11e6-9beb-d7a33d623453.PNG)
Then I followed your instructions, I use multi-scene editing and set the input module's ''Scripting Define Symbol''. I can see the hands with Leap Motion, but I can't interact with the keyboard.
Is it the problem of the Scripts Hover Input Leap Motion errors? How to fix it?
Thank you!

**Comment by zachkinstner** [comment]
@ZhengzhongSun, I don't have enough information yet... some questions:

- Which compiler errors/warnings do you see in the Unity "Console" panel? 
- Can you confirm that the `HoverInputLeapMotion` script is present in your project?
- Are you attempting to use Leap Motion's "Orion" release, or an older version?

Some notes, just in case:

- If you re-installed using the release packages (instead of cloning the project), be sure to install all the packages you'll need. For your scenario, you'd need (at least) the `Core`, `Interface-Key`, and `Input-LeapMotion` packages.
- The "scripting define symbol" must be entered exactly as `HOVER_INPUT_LEAPMOTION`.

**Comment by ZhengzhongSun** [comment]
Thank you very much!
I have re-installed using the release packages and it wroks. But I'm curious about that why there will be errors when I cloned the whole projects?

**Comment by zachkinstner** [comment]
Hi @ZhengzhongSun, when you clone the project repository, you also get the "Hover Demos" folder. The Hover UI Kit release packages do not include these demos. 

The scenes/scripts within "Hover Demos" have some additional dependencies, including the Bloom filter from Unity's "standard effects" package. So, with the cloned project, you'll see compiler errors if you don't install those effects.
