### ISSUE TITLE
How to position the Hovercast interface in world-space?

### ISSUE THREAD

**Issue by AntoineLasnier** [aestheticinteractive/Hover-VR-Interface-Kit#60]
Hi Zach ! I am looking for a simple way to have an Hovercast interface that would not be attached to the hand palm but fixed in world space. Is it possible?

**Comment by zachkinstner** [comment]
Hi @AntoineLasnier, the main Hovercast object (the one with the `HovercastInterface` component attached to it) also has a component called `HoverCursorFollower` attached to it. If you disable that component, the Hovercast interface will stop following the target cursor (by default, the "Left Palm" cursor). The Hovercast transform will no longer be set via code, so you'll be able to adjust it as usual -- you could position it in world-space, or attach it in local-space to something else in the scene.

With Hovercast in world-space, I assume that you won't want it to fade out when the interface is angled away from the camera. You can disable the `HovercastActiveDirection` component to prevent this effect. Prior to disabling this component, you'll want to make sure that Hovercast is not faded-out due to the camera angle. You could first set its "ActiveWhen Facing Transform" property to be an empty GameObject that is always positioned directly in front of Hovercast, which will ensure Hovercast appears at full visibility.

**Comment by AntoineLasnier** [comment]
Thank you for your answer. To be more specific, I would like to be able to open a world space Hovercast menu from a hand attached button (see picture). In the Hovercast prefab, that would mean that I would need to decouple the OpenButton with the rest of the menu?
![image1](https://cloud.githubusercontent.com/assets/24736103/24103379/600f1d44-0d7f-11e7-93c8-c63be1fce8e5.png)

**Comment by zachkinstner** [comment]
Hi @AntoineLasnier, once you have the world-space Hovercast in place: 

You could create a new GameObject (let's call it "HandFollower"), then attach a `HoverCursorFollower` component to it, with properties configured like Hovercast’s `HoverCursorFollower` (the one that you disabled to achieve world-space positioning). From there, move Hovercast’s “OpenItem” object into your "HandFollower" object. You’ll want your new `HoverCursorFollower` component's “Objects To Activate” list to only contain one item: the “OpenItem” object.

Now the “open” button should follow the hand, while the Hovercast interface stays fixed in world-space. The “open” button should still control the Hovercast open/close state as usual.

To get the full-circle ring in Hovercast: each "row" (the objects within “Hovercast/TransformAdjuster/Rows/…”) has a `HoverLayoutArcRow` component, just set its “Arc Degrees” property to 360.

The structure/design of the central circle is up to you. If it needs to function as a “back” button, then I’d recommend adding your custom graphics to the existing “BackItem” object. The simplest way to make the existing “BackItem” icons go away: on the “BackItem” object, set the HoverItemDataSelector component’s “Action” property to “Default” (instead of “Navigate Out”). This causes the item components to stop forcing the “back” icon to display.

**Comment by zachkinstner** [comment]
Hi @AntoineLasnier, two more questions from your email:

> I have tried to destroy the TitleItem of the Hovercast as I don’t need it but it has messed up everything as you are referencing it in several scripts. How can I destroy it then?

You're correct, the code for the Hovercast interface expects the "TitleItem" to be present. You could comment out (or wrap with a null-check) any lines that reference `HoverInterface.TitleItem`. 

A quicker alternative would be to deactivate the first/only child of the "TitleItem" object (which is its [item renderer](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Renderers)), and optionally disable all the individual components attached to the "TitleItem" object. You won't be able to deactivate the "TitleItem" object itself, since that is controlled by the Hovercast code.

> I have attached an OpenItem to each hand positioned in the middle of the palm. This works find for opening the Menu. However, when I close my hand, my index accidentally touches the button causing the menu to close. Is there a way to prevent the left index from interacting with the button on the left palm and vice versa? I want to be able to trigger the left hand button with the right hand cursor and vice versa.

Hover UI Kit doesn't currently provide a way to disable the relationship between an item and a specific cursor. While I could see that being useful in some scenarios, I think it is more likely to cause confusion, since it breaks the overall consistency of the cursor-to-item interactions.

I assume you're using Leap Motion here, so a possible solution might be to disable a fingertip cursor whenever that finger's hand is more than (for example) 50% closed into a grab. Leap Motion provides a "grab strength" property for this. 

For reference, you can disable a cursor by deactivating its associated GameObject (contained within the "HoverKit/Cursors/..." object). Alternatively, you could set the cursor's `HoverCursorData.Capability` property to be "None".
