### ISSUE TITLE
How do I add event listeners to an item?

### ISSUE THREAD

**Issue by rahb3rt** [aestheticinteractive/Hover-VR-Interface-Kit#65]
Hi, I was wondering, how do add event listeners into Hover you. ie. if I selected Item A (a checkbox) that Action A would occur. Is there a script for adding in those listeners?

Thanks in advance!

**Comment by zachkinstner** [comment]
Hi @rahb3rt, the item event handlers are located within an item's "Events" area, which can be easy to miss because it's a collapsible menu in the inspector. Each item type (checkbox, slider, etc.) has a slightly different set of events. More details on the [Items](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Items) wiki page.

Here's a screenshot of where you'll find the event handlers in the Unity inspector:

![image](https://cloud.githubusercontent.com/assets/3940764/26064159/24254a5a-395e-11e7-9b10-76c8d7e34e15.png)
