### ISSUE TITLE
I can't get started

### ISSUE THREAD

**Issue by elect86** [aestheticinteractive/Hover-VR-Interface-Kit#67]
Hi,

sorry, but I am new to Unity and I am having some issues getting started

So, this are my steps:

- creating a new 3d project

- copying the content of the Hover-UI-Kit `Assets` folder into my project ones. Unity detects it and automatically imports some stuff, scripts included.

- importing the HoverKit prefabs

- click on empty space to deselect `HoverKit`, right button, `Create Empty`, rename to `CursorRenderers`

- on the `Inspector` tab, `Add Component`, I start typing `Hov` nothing get found

![image](http://i.imgur.com/7AiWXLt.png?1)

What am I doing wrong?

**Comment by zachkinstner** [comment]
Hi @elect86! The reason Unity won't find "Hov..." in the list is because the project has errors. The red text at the bottom of the window shows that Unity can't find a dependency.

The dependency is specific to the _demos_ portion (the `/Assets/HoverDemos` folder) of the Hover UI Kit repository. The component that Hover UI Kit's demos require used to be part of Unity's "standard assets" package, but Unity has removed it. Please see [this issue](https://github.com/aestheticinteractive/Hover-UI-Kit/issues/64) to learn how to import them.

The easier alternative is to install Hover UI Kit using the [release packages](https://github.com/aestheticinteractive/Hover-UI-Kit/releases). These packages do not include any of the demo scenes/scripts, and thus, will not cause this dependency issue.

**Comment by elect86** [comment]
Ok, solved by using the Unity package files into the last release, thanks
