### ISSUE TITLE
How to attach the UI to gesture 

### ISSUE THREAD

**Issue by kunkunkunkun** [aestheticinteractive/Hover-VR-Interface-Kit#69]
Hi,Zach. I'm currently using the VR example scene in core asset and i've got my UI set up, could you tell me how can i attach hand model to the UI?  thank you ! :D

**Comment by kunkunkunkun** [comment]
![capture](https://cloud.githubusercontent.com/assets/29138261/26717489/2aeae86c-47b0-11e7-821f-25a57add8f53.PNG)
this is what i have now and i want the menu to follow my hand .

**Comment by zachkinstner** [comment]
Hi @kunkunkunkun, it's hard to say given only this screenshot, but my first guess is that you need to attach the components from the "Leap Motion" input module. Since you already have a scene with your Leap Motion hands, you'll want to use the "install this module manually" [installation instructions](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Input-Modules%EA%9E%89-LeapMotion#installation) (three steps).

Once this is done, Hover UI Kit will know how to attach cursors to the Leap Motion hands. The Hovercast interface follows the "Left Palm" cursor by default, and the "Leap Motion" input module will make sure that this cursor matches the movement and rotation of the hand.

**Comment by kunkunkunkun** [comment]
Thank you so much !! I finally get it working

**Comment by kunkunkunkun** [comment]
How i do it :
1. follow the installation instruction and 
    * if unity pop up error message saying "Can't add script because of class cannot be found", it means that 
       unity cannot find the scene , you have to give it a specific path 
      for mine i put "leapmotion_thigy/Hover/InputModules/LeapMotion/Scenes/" for the scene path folder 
      by default it should be "Hover/InputModules/LeapMotion/Scenes/"
2. go to the interface module: cast and choose the module that you want to build 

Hope this can helps other guys :D
